Feature/logout function
sudoyuichi/campground_database pull request #23
Opened 2023-12-21 13:04 UTC by EngineerTSUYOSHI

ログアウトのロジック作成用のブランチ。

[Mainからブランチを切っている為、PR22
https://github.com/sudoyuichi/campground_database/pull/22](url)
をマージ後に本ブランチをマージする事想定しております。

・修正内容
　ログアウトメソッドを作成。
　ログアウトのリンクをログインページ内に追加。

2023-12-23 07:48 UTC, sudoyuichi requested changes
コードに記した提案を確認してください。

2023-12-23 10:07 UTC, sudoyuichi requested changes
ごめん、Suggestの内容がちょっとおかしかった。

2023-12-23 10:07 UTC, sudoyuichi commented on System/Control/authControl.php
> +                $this->logout();
```suggestion
                $this->logout();
                $templateDir .= 'login.tpl';
```

2023-12-23 12:44 UTC, EngineerTSUYOSHI commented
レビューに基づきログアウト後の画面遷移方法を修正。

セッション開始についてはログアウト時にエラーを起こす為
コンストラクタでセッション開始する事で解決。
`エラー内容`
Warning: session_destroy(): Trying to destroy uninitialized session in /Applications/MAMP/htdocs/campground_database/System/Control/authControl.php on line 173

いまいち理由が分からないが
セッション開始時はヘッダに何も持たせない様にする必要があり
executeメソッド内で呼び出すと上手くセッションができてないっぽい？

2023-12-24 01:31 UTC, sudoyuichi commented
@EngineerTSUYOSHI 
とりあえず、エラーがなぜ起こるかについて等は、後にします。
一旦このままマージします。

2023-12-24 01:31 UTC, merged